<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ProjectsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('projects')->insert([
            ['date' => '2001-11-02', 'title' => 'Hambatan Perdagangan Bebas Dan Investasi Di Jawa Timur', 'client_id' => 1, 'kategori_id' => 1],
            ['date' => '2002-07-04', 'title' => 'Survey On Decentralization And Bussiness', 'client_id' => 1, 'kategori_id' => 1],
            ['date' => '2002-11-01', 'title' => 'Survey On Decentralization And Bussiness (Tahap II)', 'client_id' => 2, 'kategori_id' => 1],
            ['date' => '2003-04-15', 'title' => 'Policy Workshop \'Survey Results On Perception Of Business Owners Toward Decentralization And Its Impact On Business Climate In Surabaya, Bandar Lampung And Manado\'', 'client_id' => 2, 'kategori_id' => 1],
            ['date' => '2003-04-28', 'title' => 'Policy Workshop \'Cooperation Model Among Financial Institution In Distributing Small Scale Business Credit (KUK) In East Java\'', 'client_id' => 1, 'kategori_id' => 1],
            ['date' => '2003-07-25', 'title' => 'The Finance For Small And Medium Enterprise Study', 'client_id' => 3, 'kategori_id' => 1],
            ['date' => '2003-08-14', 'title' => 'Penyusunan Perencanaan Jangka Menengah Pengembangan Industri Kecil Di Tuban', 'client_id' => 4, 'kategori_id' => 1],
            ['date' => '2003-09-10', 'title' => 'Survey On The Effectiveness of Coordination Among Local Governments In East Java In Improving Business Climate', 'client_id' => 2, 'kategori_id' => 1],
            ['date' => '2004-01-15', 'title' => 'The Finance For Small And Medium Enterprise Study (Tahap II - FGD)', 'client_id' => 3, 'kategori_id' => 1],
            ['date' => '2004-03-11', 'title' => 'Study And Advocacy: Investment Barriers In Eastern Indonesia For The Foreign Direct Investment From European Union Countries', 'client_id' => 5, 'kategori_id' => 1],
            ['date' => '2004-04-15', 'title' => 'Bupati/Mayors Forum on Domestic Trade Barriers In East Java', 'client_id' => 2, 'kategori_id' => 1],
            ['date' => '2004-10-31', 'title' => 'Program On Mapping Potential Export Commodities And Improvement Access to European Union Countries Market For Enterprises In East Java', 'client_id' => 5, 'kategori_id' => 1],
            ['date' => '2005-06-08', 'title' => 'Surabaya Vision Plan 2005 - 2025 Project', 'client_id' => 6, 'kategori_id' => 1],
            ['date' => '2005-06-09', 'title' => 'Local Governance Rapid Assessment Method (LG-RAM)', 'client_id' => 7, 'kategori_id' => 1],
            ['date' => '2005-07-01', 'title' => 'Internal Assessment Of Technical Assistance To OSS In Kediri City And Jogjakarta City', 'client_id' => 2, 'kategori_id' => 1],
            ['date' => '2005-07-14', 'title' => 'Penyediaan Jasa Penelitian Pemetaan Peraturan Daerah Dan Potensi Dampaknya Terhadap Pertumbuhan Ekonomi Dan Inflasi Di Jawa Timur', 'client_id' => 8, 'kategori_id' => 1],
            ['date' => '2005-07-15', 'title' => 'Local Governance Activity Mapping Protocol (LG-AMP)', 'client_id' => 7, 'kategori_id' => 1],
            ['date' => '2005-10-27', 'title' => 'BPRs & LPDs Customer Satisfaction Survey', 'client_id' => 9, 'kategori_id' => 1],
            ['date' => '2006-03-20', 'title' => 'Penyediaan Jasa Penelitian Potensi Dampak Ekonomi Dan Sosial Blok Migas Cepu Bagi Jawa Timur', 'client_id' => 8, 'kategori_id' => 1],
            ['date' => '2006-07-01', 'title' => 'Workshop Reformasi Birokrasi', 'client_id' => 10, 'kategori_id' => 1],
            ['date' => '2006-08-22', 'title' => 'Dissemination of BPR & LPDs Customer Satisfaction Survey Result', 'client_id' => 9, 'kategori_id' => 1],
            ['date' => '2006-11-13', 'title' => 'Survey Kepuasan Nasabah BPR', 'client_id' => 11, 'kategori_id' => 1],
            ['date' => '2006-11-17', 'title' => 'Survey Kepuasan Publik Terhadap Pelayanan Sektor Swasta', 'client_id' => 12, 'kategori_id' => 1],
            ['date' => '2006-12-01', 'title' => 'Survey Analisa Ekonomi Daerah', 'client_id' => 13, 'kategori_id' => 1],
            ['date' => '2007-05-09', 'title' => 'Studi Hambatan Daya saing Industri Furniture Di Jawa Timur dan Jawa Tengah', 'client_id' => 14, 'kategori_id' => 1],
            ['date' => '2007-06-11', 'title' => 'Penyusunan Buku Pengkajian Potensi Agro Kecamatan Wonosalam', 'client_id' => 15, 'kategori_id' => 1],
            ['date' => '2007-06-12', 'title' => 'Survei Akses keuangan Di Indonesia', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2007-10-09', 'title' => 'Assessment Non Formal Education Program', 'client_id' => 16, 'kategori_id' => 2],
            ['date' => '2007-10-09', 'title' => 'Kajian Kemungkinan Penggunaan Dana Pemda Sebagai Penjaminan Pembiayaan UMKM Di Jawa Timur', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2008-02-11', 'title' => 'Market Survey for furniture Industry', 'client_id' => 16, 'kategori_id' => 1],

            ['date' => '2008-05-06', 'title' => 'Penelitian Pemetaan Profil BPR Dalam Rangka Penyusunan Stratifikasi Industri BPR', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2008-06-06', 'title' => 'Certification for Teacher on Structural Position', 'client_id' => 18, 'kategori_id' => 2],
            ['date' => '2008-06-19', 'title' => 'The Household Survey on Access to Financial Services for Migrant Workers and Their Family in NTT & NTB', 'client_id' => 19, 'kategori_id' => 1],
            ['date' => '2008-06-26', 'title' => 'The Household Survey on Access to Financial Services for Migrant Workers and Their Family in NTT & NTB', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2008-09-26', 'title' => 'MCLE Baselines Survey', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2008-07-01', 'title' => 'Vehicle Ownership Survey in Surabaya, Sidoarjo and Gresik', 'client_id' => 20, 'kategori_id' => 3],
            ['date' => '2009-01-05', 'title' => 'SPHR 2009', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2009-01-26', 'title' => 'Trade Finance', 'client_id' => 22, 'kategori_id' => 1],
            ['date' => '2009-04-30', 'title' => 'ILO - Mapping', 'client_id' => 23, 'kategori_id' => 1],
            ['date' => '2009-05-26', 'title' => 'Survei Dampak Krisis Keuangan Global Terhadap Usaha Besar/Menengah', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2009-07-01', 'title' => 'MFIs Survey in East Java', 'client_id' => 23, 'kategori_id' => 1],
            ['date' => '2009-07-21', 'title' => 'MFIs Survey in Yogyakarta and Central Java', 'client_id' => 12, 'kategori_id' => 1],
            ['date' => '2009-07-31', 'title' => 'BPRS Customer Satisfaction Survey', 'client_id' => 12, 'kategori_id' => 1],
            ['date' => '2009-08-07', 'title' => 'Study of the implementation of KUR at the local level', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2009-09-28', 'title' => 'Market Research for Mobile Banking in Indonesia', 'client_id' => 24, 'kategori_id' => 1],
            ['date' => '2010-01-05', 'title' => 'Survei Harga Properti Residensial', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2010-01-18', 'title' => 'Survey of 394 household in East Java, West Java & Banten', 'client_id' => 25, 'kategori_id' => 3],
            ['date' => '2010-02-03', 'title' => 'Financial Literacy Training & Survey', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2010-02-07', 'title' => 'Growth Diagnostic Study for East Java', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2010-06-14', 'title' => 'Survey on Mobile - Enabled Brancless Banking Capacity', 'client_id' => 26, 'kategori_id' => 1],
            ['date' => '2010-09-21', 'title' => 'Penelitian Daya Saing Perbankan Di Pasar Kredit Mikro Di Jawa Timur', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2010-10-15', 'title' => 'MSME Nigeria - to arrange logistics & coordinate a study to Indonesia', 'client_id' => 27, 'kategori_id' => 1],
            ['date' => '2010-09-08', 'title' => 'Penyusunan Indikator Ketenagakerjaan', 'client_id' => 13, 'kategori_id' => 1],
            ['date' => '2011-01-05', 'title' => 'Survei Konsumen', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2011-01-10', 'title' => 'Survei Harga Properti Residensial', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2011-03-10', 'title' => 'BID 1 Financial Literacy Training', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2011-03-19', 'title' => 'Impact of Free Trade Agreements on Business Activity', 'client_id' => 28, 'kategori_id' => 1],
            ['date' => '2011-04-27', 'title' => 'Survei Kinerja Zakat Dalam Pengentasan Kemiskinan Wilayah Surabaya', 'client_id' => 29, 'kategori_id' => 1],
            ['date' => '2011-06-10', 'title' => 'Penyusunan Identifikasi Kebutuhan Pasar Kerja di Kota Surabaya', 'client_id' => 13, 'kategori_id' => 1],
            ['date' => '2011-09-05', 'title' => 'Survei Pemetaan Struktur Pasar Dan Pola Distribusi Komoditas Strategis Penyumbang Inflasi Daerah', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2011-10-18', 'title' => 'TOT Edukasi Perbankan & Remitansi', 'client_id' => 30, 'kategori_id' => 1],
            ['date' => '2011-10-01', 'title' => 'Manajemen Resiko', 'client_id' => 31, 'kategori_id' => 1],
            ['date' => '2011-11-10', 'title' => 'TOT tentang Edukasi Keuangan Kepada TKI', 'client_id' => 32, 'kategori_id' => 1],
            ['date' => '2011-12-12', 'title' => 'Monitoring & Evaluasi Trainers terkait Edukasi Keuangan Kepada TKI di Sumbawa Besar NTB', 'client_id' => 32, 'kategori_id' => 1],
            ['date' => '2012-01-05', 'title' => 'Survei Konsumen', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2012-01-05', 'title' => 'Survei Harga Properti Residensial', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2012-02-13', 'title' => 'Survei Kegiatan Dunia Usaha Di Pulau Lombok', 'client_id' => 32, 'kategori_id' => 1],
            ['date' => '2012-07-13', 'title' => 'Analisis Tingkat Persaingan Usaha Bank di Tingkat Provinsi', 'client_id' => 33, 'kategori_id' => 1],
            ['date' => '2012-09-04', 'title' => 'Identifying the constraints to inclusive growth in west nusa tenggara', 'client_id' => 34, 'kategori_id' => 3],
            ['date' => '2012-09-04', 'title' => 'The Impact of Infrastructure Expenditure on Economic Development in East Java: Analyzing Local Government Spending on Infrastructure and its Impact on Economic Growth and Poverty Alleviation in East Java Province', 'client_id' => 35, 'kategori_id' => 1],
            ['date' => '2012-11-01', 'title' => 'Study of the Impact of Branchless Banking on Increasing Access to Financial Services for Households, KPW Bank Indonesia East Java Province', 'client_id' => 36, 'kategori_id' => 1],
            ['date' => '2013-01-14', 'title' => 'Survei Penjualan Eceran', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2013-01-25', 'title' => 'Survei Kegiatan Dunia Usaha Di Pulau Lombok 2013', 'client_id' => 37, 'kategori_id' => 1],
            ['date' => '2013-01-30', 'title' => 'Strengthening Local of Chamber of Commerce in Improving Investment and Trade Environment in Eastern Indonesia through the Establishment of Centre for Investment and Trade Advisory (CITRA)', 'client_id' => 38, 'kategori_id' => 1],
            ['date' => '2013-02-14', 'title' => 'Perolehan Series Data Regional Macroeconomic Model of Bank Indonesia', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2013-02-28', 'title' => 'Conducting Field Level Survey in NTT and Java Island', 'client_id' => 39, 'kategori_id' => 1],
            ['date' => '2013-02-28', 'title' => 'Institutional Small FOG Application', 'client_id' => 40, 'kategori_id' => 1],
            ['date' => '2013-03-14', 'title' => 'Quick Survey "Analisis Kinerja Sektor Konstruksi dan Properti"', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2013-05-15', 'title' => 'Baseline Survey for the Evaluation of the Education Partnership - Component 1 (School Construction)', 'client_id' => 41, 'kategori_id' => 2],
            ['date' => '2013-07-01', 'title' => 'PNPM Mandiri RLF Capacity Building', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2013-08-27', 'title' => 'Serviced Covered under the evaluation of USAID/Indonesia Program Opportunities for Vulnerable Children (OVC)', 'client_id' => 41, 'kategori_id' => 3],
            ['date' => '2013-10-28', 'title' => 'Analytical and Capacity Development Partnership (ACDP)', 'client_id' => 42, 'kategori_id' => 1],
            ['date' => '2013-11-18', 'title' => 'Conducting Qualitative Survey in East Java and West Java', 'client_id' => 39, 'kategori_id' => 1],
            ['date' => '2013-11-22', 'title' => 'Seminar Manajemen Resiko Tata Kelola Untuk Membangun Nilai', 'client_id' => 43, 'kategori_id' => 1],
            ['date' => '2013-12-31', 'title' => 'Survei Kegiatan Dunia Usaha Di Pulau Lombok 2014', 'client_id' => 32, 'kategori_id' => 1],
            ['date' => '2014-01-06', 'title' => 'Survei Penjualan Eceran Th 2014', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2014-02-25', 'title' => 'Market Survei for Mobile Payment Demand Assessment in Indonesia', 'client_id' => 44, 'kategori_id' => 1],
            ['date' => '2014-04-01', 'title' => 'Final Inclusion Needs Assessment', 'client_id' => 41, 'kategori_id' => 3],
            ['date' => '2014-05-01', 'title' => 'BID 1 Local Level Workshop PNPM Mandiri', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2014-07-14', 'title' => '2014 AIBEP Schools Survey : Data Collection & Cleaning', 'client_id' => 41, 'kategori_id' => 2],
            ['date' => '2014-06-02', 'title' => 'ACDP 042 Pilot Test', 'client_id' => 18, 'kategori_id' => 3],
            ['date' => '2015-01-05', 'title' => 'Survei Konsumen', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2015-01-14', 'title' => 'Indonesia PRIORITAS Mid Term Evaluation', 'client_id' => 45, 'kategori_id' => 1],
            ['date' => '2015-02-16', 'title' => 'ACDP 042 - Survey Implementation', 'client_id' => 18, 'kategori_id' => 3],
            ['date' => '2015-05-15', 'title' => 'Jasa Survei Biaya Logistik dan Pola Perdagangan Antar Wilayah 2015', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2015-05-25', 'title' => 'EOPO 1 Evaluation Study-Household Survey', 'client_id' => 41, 'kategori_id' => 3],
            ['date' => '2015-05-27', 'title' => 'Corruption Survey', 'client_id' => 46, 'kategori_id' => 1],
            ['date' => '2015-08-28', 'title' => 'Kajian Kemungkinan Pendirian Perusahaan Penjamin Ulang', 'client_id' => 47, 'kategori_id' => 1],
            ['date' => '2016-01-06', 'title' => 'Survei Konsumen Di Kota Surabaya', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2016-01-20', 'title' => 'Survei Pemanfaatan Dana Desa', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2016-03-01', 'title' => 'Survei Kegiatan Dunia Usaha Di Ambon', 'client_id' => 48, 'kategori_id' => 1],
            ['date' => '2016-10-05', 'title' => 'Survei Outbond', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2016-10-14', 'title' => 'Survei Inovasi', 'client_id' => 49, 'kategori_id' => 1],
            ['date' => '2016-10-24', 'title' => 'Survei Kontribusi Kawasan Industri Dalam Peningkatan Daya Saing Industri Di Jawa Timur', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2016-12-30', 'title' => 'Survei Konsumen di Kota Ambon', 'client_id' => 48, 'kategori_id' => 1],
            ['date' => '2017-01-05', 'title' => 'Survei Konsumen Di Kabupaten Jember', 'client_id' => 50, 'kategori_id' => 1],
            ['date' => '2017-01-18', 'title' => 'Inovasi', 'client_id' => 49, 'kategori_id' => 1],
            ['date' => '2017-02-28', 'title' => 'Survei Kegiatan Dunia Usaha Di Ambon', 'client_id' => 48, 'kategori_id' => 1],
            ['date' => '2017-03-21', 'title' => 'Employer Survey Data Collection', 'client_id' => 51, 'kategori_id' => 1],
            ['date' => '2017-11-05', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Kalimantan Utara', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2017-09-27', 'title' => 'Survei Penurunan Konsumsi dan Pendalaman Aktivitas e-Commerce Masyarakat', 'client_id' => 48, 'kategori_id' => 1],
            ['date' => '2017-12-22', 'title' => 'Survei Harga Properti Residensial', 'client_id' => 21, 'kategori_id' => 1],
            ['date' => '2017-12-29', 'title' => 'Survei Konsumen Kota Ambon', 'client_id' => 48, 'kategori_id' => 1],
            ['date' => '2017-12-29', 'title' => 'Survei Kegiatan Dunia Usaha Di Ambon', 'client_id' => 48, 'kategori_id' => 1],
            ['date' => '2017-01-04', 'title' => 'Survei Konsumen Di Kabupaten Jember', 'client_id' => 50, 'kategori_id' => 1],
            ['date' => '2018-01-10', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Nusa Tenggara Barat (WO 1)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-01-31', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Nusa Tenggara Timur (WO 2)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-02-06', 'title' => 'Survei Kegiatan Dunia Usaha (SKDU) Jember', 'client_id' => 50, 'kategori_id' => 1],
            ['date' => '2018-03-09', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Nusa Tenggara Timur (WO 3)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-03-09', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Nusa Tenggara Barat (WO 4)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-04-13', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - SLA (SUB 015)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-07-20', 'title' => 'Jasa Konsultasi Penasehat Keuangan Penerbitan Saham Seri B Bank Bengkulu', 'client_id' => 52, 'kategori_id' => 1],
            ['date' => '2018-07-26', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - NTB Endline (WO 1)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-08-20', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - East Java (WO 2)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-09-24', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Grantee (WO 3)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-10-28', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - East Java 2 (WO 4)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-11-14', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Additional Schools (WO 5)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-11-24', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - Additional Schools (WO 6)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2018-12-28', 'title' => 'Survei Konsumen Kota Jember', 'client_id' => 50, 'kategori_id' => 1],
            ['date' => '2018-12-31', 'title' => 'Survei Konsumen Kota Maluku', 'client_id' => 48, 'kategori_id' => 1],
            ['date' => '2019-01-28', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - East Java (WO 7)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-03-05', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - East Java (WO 7A)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-02-25', 'title' => 'Rural Poverty Assessment Field Survey', 'client_id' => 53, 'kategori_id' => 3],
            ['date' => '2019-03-04', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - North Kalimantan (WO 008)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-02-20', 'title' => 'Survei Kegiatan Dunia Usaha (SKDU) Jember', 'client_id' => 50, 'kategori_id' => 1],
            ['date' => '2019-03-21', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - East Java (WO 009)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-02-27', 'title' => 'Survei Kegiatan Dunia Usaha (SKDU) Ambon', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2019-03-25', 'title' => 'Survei Harga Properti Residensial (SHPR) Surabaya', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2019-07-31', 'title' => 'Rural Poverty Assessment Field Survey Round 2', 'client_id' => 53, 'kategori_id' => 3],
            ['date' => '2019-08-13', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - SUB 018', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-08-13', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - SUB 021', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-08-13', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - SUB 022', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-08-13', 'title' => 'Survei Inovasi Pendidikan Dan Pembelajaran Indonesia - SUB 023', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2019-12-24', 'title' => 'Impact Evaluation of Subnational Infrastructure Investment in Indonesia', 'client_id' => 53, 'kategori_id' => 1],
            ['date' => '2019-12-27', 'title' => 'Survei Konsumen (SK) Jember + Banyuwangi', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2019-12-31', 'title' => 'Survei Konsumen (SK) Maluku', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2020-01-20', 'title' => 'Australia Indonesia Partnership The Innovation for Indonesia The Innovation for indonesia\'s School Children (INOVASI) Program', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2020-02-17', 'title' => 'Survei Harga Properti Residensial (SHPR) Surabaya', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2020-03-02', 'title' => 'Impact Evaluation of KUR Program - Data Collection for follow up survey', 'client_id' => 53, 'kategori_id' => 1],
            ['date' => '2020-03-02', 'title' => 'Survei Kegiatan Dunia Usaha (SKDU) Ambon', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2020-04-06', 'title' => 'MADANI Baseline Data Collection', 'client_id' => 54, 'kategori_id' => 1],
            ['date' => '2020-10-09', 'title' => 'Rapid Impact Women\'s Empowerment Framework', 'client_id' => 56, 'kategori_id' => 1],
            ['date' => '2020-11-24', 'title' => 'Pelaksanaan Preferensi Wisatawan Domestik Pasca Covid-19', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2020-12-30', 'title' => 'Survei Konsumen (SK) Jember 2021', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2020-12-30', 'title' => 'Survei Konsumen (SK) Maluku 2021', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2021-01-22', 'title' => 'Survei Preferensi Wisatawan (Pariwisata) Di Surabaya Tahun 2021', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2021-01-26', 'title' => 'Study Gender Responsive Value Chain And Entrepreneurship Development Programme - PO-2101-0028', 'client_id' => 56, 'kategori_id' => 3],
            ['date' => '2021-02-25', 'title' => 'Survei Kegiatan Dunia Usaha (SKDU) Ambon', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2021-03-01', 'title' => 'Survei Harga Properti Residensial (SHPR) Surabaya', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2021-03-12', 'title' => 'Gender Equality and Social Inclusion (GESI) in Mass Transit in Bandung', 'client_id' => 53, 'kategori_id' => 3],
            ['date' => '2021-03-26', 'title' => 'Data Collection for the Situational Analysis of Learning Gaps and Effect of COVID-19 on Participation in Schooling in Indonesia during 2020/2021 Academic Year', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2021-03-22', 'title' => 'Status of Women owned MSMEs in three provinces - North Sulawesi, South Sumatra & Riau', 'client_id' => 57, 'kategori_id' => 3],
            ['date' => '2021-08-23', 'title' => 'Organisation and school-level baseline (for Muhammadiyah and Ma\'arif NU) in scaling out INOVASI literacy and numeracy approach in East Java (IDINO2-SUB-015-0621)', 'client_id' => 49, 'kategori_id' => 3],
            ['date' => '2021-09-15', 'title' => 'Social Network Analysis (SNA) Survey', 'client_id' => 58, 'kategori_id' => 4],
            ['date' => '2021-10-25', 'title' => 'Organisation and school-level baseline (for UNAIR, UMSIDA and SAKB) to implement Character Education Pilot in East Java (Lamongan and Sidoarjo) and NTT (West Sumba) and Gender Responsive Learning Pilot in East Java (Sidoarjo) (IDINO2-SUB-017-1021)', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2021-11-26', 'title' => 'Survei Preferensi Wisatawan Nusantara Pada Masa Adaptasi Kebiasaan Baru Di Surabaya', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2021-12-16', 'title' => 'Survei Harga Properti Residensial (SHPR) 2022 Surabaya', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2022-01-11', 'title' => 'Survei Midline MADANI 2022', 'client_id' => 54, 'kategori_id' => 1],
            ['date' => '2022-02-06', 'title' => 'Study on Assessment and Scalability of the 21st Century Skills Programme', 'client_id' => 18, 'kategori_id' => 2],
            ['date' => '2022-03-02', 'title' => 'Survei Kegiatan Dunia Usaha (SKDU) Papua Barat 2022', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2022-03-11', 'title' => 'Survei Kegiatan Dunia Usaha (SKDU) Ambon 2022 - 2023', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2022-06-15', 'title' => 'SES & IBL Program', 'client_id' => 18, 'kategori_id' => 2],
            ['date' => '2022-06-23', 'title' => 'Angkot Operator/Crew Qualitative Study', 'client_id' => 16, 'kategori_id' => 3],
            ['date' => '2022-07-25', 'title' => 'Study of childcare service in Indonesia', 'client_id' => 16, 'kategori_id' => 2],
            ['date' => '2022-10-21', 'title' => 'Childcare Study in Indonesia - Indonesian Gender PASA', 'client_id' => 16, 'kategori_id' => 2],
            ['date' => '2022-08-31', 'title' => 'IDINO2-SUB-021-0822 Initial Assessment Study on Book Provision for School In INOVASI Four (4) Partner Provinces', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2023-02-01', 'title' => 'Rajawali: Expanding Financial Access Points in Flores, East Indonesia using agent-network managers', 'client_id' => 16, 'kategori_id' => 4],
            ['date' => '2023-03-03', 'title' => 'Survei Konsumen (SK) Maluku 2023', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2023-02-13', 'title' => 'Survei Harga Properti Residensial Primer KPwBI Tahun 2023', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2023-03-24', 'title' => 'Pilot test plan: Mitra Bukalapak expansion in Tier 3 cities', 'client_id' => 59, 'kategori_id' => 4],
            ['date' => '2023-03-30', 'title' => 'Survei Kegiatan Dunia Usaha KPwBI Papua Barat 2023', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2023-04-28', 'title' => 'Final Assessment on Book Provision for School in Four INOVASI Partner Provinces', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2023-07-11', 'title' => 'Data Collection for Social Network Analysis Survey in 31 MADANI Districts', 'client_id' => 54, 'kategori_id' => 1],
            ['date' => '2023-07-15', 'title' => 'Endline Data Collection for MADANI Project', 'client_id' => 54, 'kategori_id' => 1],
            ['date' => '2024-01-29', 'title' => 'Adendum Survei Konsumen (SK) Kota Ambon 2023', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2024-02-06', 'title' => 'Household Data Collection', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2024-02-28', 'title' => 'Survei Konsumen (SK) Kota Ambon Periode Maret 2024 - Februari 2025', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2024-02-29', 'title' => 'Survei Harga Properti Residensial Primer KPwBI Tahun 2024', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2024-02-29', 'title' => 'Survei Kegiatan Dunia Usaha KPwBI Maluku 2024', 'client_id' => 17, 'kategori_id' => 1],
            ['date' => '2024-04-01', 'title' => 'Follow-Up Qualitative Study on The Implementation of the High-Tech High-Touch Teaching Approach in Public Junior High Schools, Indonesia', 'client_id' => 60, 'kategori_id' => 2],
            ['date' => '2024-05-25', 'title' => 'Educational Situational Analysis in Penajam Paser Utara district, Ibu Kota Nusantara (IKN) - 8 Schools', 'client_id' => 49, 'kategori_id' => 2],
            ['date' => '2024-08-02', 'title' => 'Study on Output and Outcome of Teaching based Social Emotional Skills (SES) Program in Kudus', 'client_id' => 18, 'kategori_id' => 2],
            ['date' => '2024-08-02', 'title' => 'Phone Survey of Pekka Cadres', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2024-09-03', 'title' => 'Market Research Developing Sanitation Solution For The Communities Of Komida Members Along The Riverbanks In Banjarmasin Area', 'client_id' => 61, 'kategori_id' => 3],
            ['date' => '2024-10-14', 'title' => 'Digital Merchant Payment', 'client_id' => 62, 'kategori_id' => 4],
            ['date' => '2024-10-15', 'title' => 'Business Case Research for Family-Friendly Workplaces', 'client_id' => 16, 'kategori_id' => 1],
            ['date' => '2024-11-28', 'title' => 'Trade Facilitation Agreement (TFA) Implementation Survey', 'client_id' => 63, 'kategori_id' => 1],
            ['date' => '2024-12-10', 'title' => 'Household Data Collection - Phase 2', 'client_id' => 16, 'kategori_id' => 1],
        ]);
    }
}
